### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by asadm** [Chippd/css_loading_animation#1]
This is awesome! 
I would love to use this in my side projects sometime. Can you add a license. This should help: https://choosealicense.com/

**Comment by chriscn** [comment]
Plus one on getting a license. MIT would be great but completely up to you

**Comment by Chippd** [comment]
Sorry guys I'm trying to figure this out. Basically what I'd like is that it's free for non commercial purposes, but a paid license is required for commercial purposes. Does such a license exist? I would think that it would.

@asadm thank you for the link, it's helpful but I'm still a little lost, there isn't an obvious license to pick...

**Comment by Chippd** [comment]
Added MIT license, will re-visit the commercial side of it in a while :)
